### PR TITLE
Update amdgpu and radeonkms firmwares

### PR DESCRIPTION
**Pull request by zeising**
Update amdgpu and radeonkms firmwares to the latest version.
This is current with linux-firmware commit
8ba6fa665c52093ddc0d81137fc3c82cee2c5ef8

This adds new firmware for renoir and navi14_ta.  Hook these to the
build.

### CODE REVIEW

**Comment by zeising** [comment]
@iotamudelta  Can you have a look if this is in any way sensible. Thanks!

**Comment by zeising** [comment]
I have a patch for the port.  I'll update it tomorrow (when I'm more awake) unless you beat me to it. :)

**Comment by iotamudelta** [comment]
No, feel free to do it - no need to have two patches.

**Comment by zeising** [comment]
Hm, on second thought. Hold off for a bit if possible. I'll look into the Intel firmware side as well tomorrow, and see if there's anything needing to be done there.

**Pull request merged**
