### PR TITLE
Connect Kabylake GuC v9.39 for drm-v5.0 or later

### PR DESCRIPTION
**Pull request by wulf7**
It works with drm-devel-kmod 5.2. At least, I am able to start X-server with it.

### CODE REVIEW

**Comment by iotamudelta** [comment]
@zeising how can we check that this remains working w/ the older Linux DRMs? I'll merge and update the port once we have that confirmation.

**Comment by wulf7** [comment]
> LGTM - however, before we can update the firmware port I'd like confirmation that this works also across the older Linux DRMs for older FBSD releases.

It does not work for me at least on 4.16 but it is disabled by default
One should explicitly add compat.linuxkpi.i915_enable_guc=<some value> to /boot/loader.conf to load GUC/HUC firmware

**Comment by wulf7** [comment]
drm-devel-kmod 5.4 requires newer guc/huc firmwares.

**Comment by zeising** [comment]
So we should install multiple versions of the firmware files?

**Comment by wulf7** [comment]
> So we should install multiple versions of the firmware files?

I did not quite understand what you meant.
Different versions of drm-kmod may require different firmwares.
GUC/HUC firmwares requires standard DMC firmware to work.
Intel's firmwares do not conflict with each other as their name contain a version number, so we can provide multiple versions in a single bundle if necessary,

**Pull request closed without merging**
